name: 'sbt install'
description: 'sbt install'
inputs:
       sbt-version: 
        description: 'The sbt version to use'
        default: '1.1.1'
        required: false
runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: Jtalk/setup-sbt@v1
        with:
          version: ${{inputs.sbt-version}}
      - name: version check
        shell: bash
        run: sbt -version

