name: 'sbt install'
description: 'sbt install'
runs:
  using: "composite"
  steps:
      - uses: Jtalk/setup-sbt@v1
        with:
           version: 1.1.1
      - name: version check
        shell: bash
        run: sbt -version

