name: 'sbt install'
description: 'sbt install'
runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: Jtalk/setup-sbt@v1
        with:
        sbt-version: ${{ inputs.sbt-version }}
      - name: version check
        shell: bash
        run: sbt -version

